name: lint

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.25

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --config=tools/lint.yml
