name: go vet test

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download statictest binary
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: statictest
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Disable VCS stamping
        run: echo "GOFLAGS=-buildvcs=false" >> $GITHUB_ENV

      - name: Run statictest
        run: |
          for pkg in $(go list ./...); do
            if [[ "$pkg" == *"/internal/api" ]]; then
              # исключаем generated.go в этом пакете
              files=$(go list -f '{{range .GoFiles}}{{$.Dir}}/{{.}} {{end}}' "$pkg" | tr ' ' '\n' | grep -v 'internal/api/generated.go' || true)
              if [ -n "$files" ]; then
                go vet $files
              fi
            else
              go vet "$pkg"
            fi
          done
      
